name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub (optional, if pushing to a registry)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/health-check:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/health-check:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/health-check:latest

      # Step 4: Push the Docker image (optional)
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/health-check:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/health-check:latest
